FileVersion = 1

[Project]
Name = "libexpat-beef"
TargetType = "BeefLib"
StartupObject = "libexpat_beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libexpat-MD.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libexpat-dMD.lib"]
